spring.application.name=progress-tracking-management
server.port=8085

# Point back to jobtrack_db to keep your jobs/skills data
spring.datasource.url=jdbc:mysql://localhost:3306/jobtrack_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
