INSERT INTO skills (skill_name, category) VALUES
('Java', 'Java'),
('Python', 'Python'),
('JavaScript', 'JavaScript'),
('C#', 'C#'),
('C++', 'C++'),
('SQL', 'SQL'),
('HTML', 'HTML'),
('CSS', 'CSS'),
('React', 'React'),
('Angular', 'Angular'),
('Node.js', 'Node.js'),
('Spring Boot', 'Spring Boot'),
('Django', 'Django'),
('Flask', 'Flask'),
('MongoDB', 'MongoDB'),
('MySQL', 'MySQL'),
('PostgreSQL', 'PostgreSQL'),
('Git', 'Git'),
('Docker', 'Docker'),
('Kubernetes', 'Kubernetes');